### ISSUE TITLE
Password generation

### ISSUE THREAD

**Issue by cimbalo** [LILiK-117bis/lilik_playbook#10]
Instead of using **library/gen_passwd.py** we can generate a password using lookup

```
- name: read password
  set_fact:
    password: "{{ lookup('password') }}"
```

Then save it to a remote file using shell and echo redirection and after read the file with shell and cat command (or we can find better option than using shell module).

**Comment by edoput** [comment]
A little more context [lookup](http://docs.ansible.com/ansible/playbooks_lookups.html#id4). It generate a random password and save it to a file on the ~~remote~~ local

``` yaml
- name:  assign password
  set_fact:
    password: "{{ lookup('password', '/path/to/local/file') }}"
```

the use the `password` variable in our playbook. If the file does not exist it creates a password and fill the file, otherwise it reads the password from the file.

Edit: the file is local not remote
