### ISSUE TITLE
Ansible version WTF

### ISSUE THREAD

**Issue by edoput** [LILiK-117bis/lilik_playbook#13]
> Lasciate ogni speranza o voi ch'entrate

- ansible 2.3 is fucked
- ansible 2.2 is fucked
- ansible 2.1 

ansible 2.3 won't let you define a connection for a role as a parameter

This won`t work
```yaml
roles:
  - role:  pippo
    ansible_connection: lxc_ssh
```
ansible 2.2, 2..1 won't fire handlers other that the first when imported with a role or include statement
